project:
  type: book
  output-dir: docs

book:
  title: "Minicurso A-Frame VR para Ensino de Física e Astronomia"  
  author: "João Teles"
  date: "17/10/2024"
  search: true
  repo-url: https://jocoteles.github.io/Minicurso-A-Frame-VR/
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  chapters:        
    - index.qmd
    - htmlbasico.qmd
    - projetoSTL.qmd
    - referencias.qmd  

bibliography: references.bib

format:
  html:
    theme: cosmo
    lang: pt
  pdf:
    documentclass: scrreprt



