project:
  type: book
  output-dir: docs

book:
  title: "Minicurso: Realidade Virtual com A-Frame para Ensino de Física e Astronomia"  
  author: "João Teles"
  date: "10/17/2024"
  search: true
  repo-url: https://jocoteles.github.io/Minicurso-A-Frame-VR/
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  chapters:        
    - index.qmd
    - htmlbasico.qmd
    - projetoSTL.qmd
    - referencias.qmd  

crossref:
  custom:
    - kind: float
      reference-prefix: Vídeo
      key: vid
    - kind: float
      reference-prefix: Código
      key: cod


bibliography: references.bib

format:
  html:
    theme: cosmo
    lang: pt
  pdf:
    documentclass: scrreprt



