project:
  type: book
  output-dir: docs  

book:
  title: "Realidade Virtual com A-Frame para Ensino de Física e Astronomia"  
  author: "João Teles de Carvalho Neto"
  date: "10/17/2024"
  cover-image: Logo-minicurso-AFrame-Astronomia.png
  search: true
  repo-url: https://github.com/jocoteles/Minicurso-A-Frame-VR
  repo-actions: [edit]
  sharing: [twitter, facebook]  
  chapters:        
    - index.qmd
    - htmlbasico.qmd
    - projetoSTL.qmd 
    - referencias.qmd

crossref:
  custom:
    - kind: float
      reference-prefix: Vídeo
      key: vid
    - kind: float
      reference-prefix: Código
      key: cod


bibliography: references.bib

format:
  html:
    theme: journal
    lang: pt
  pdf:
    documentclass: book
    toc: true
    toc-depth: 2
    number-sections: true
    geometry:
      - top=30mm
      - bottom=30mm
      - left=25mm
      - right=25mm
    fontsize: 12pt
    mainfont: "Times New Roman"
    sansfont: "Arial"
    monofont: "Courier New"
    colorlinks: true
    linkcolor: blue
    citecolor: red
    urlcolor: magenta
    include-in-header:
      - text: |
          \usepackage{fancyhdr}
          \pagestyle{fancy}
          \fancyhf{}
          \rhead{\thepage}
          \lhead{\leftmark}



