project:
  type: book

book:
  title: "Minicurso A-Frame VR"  
  author: "João Teles"
  date: "17/10/2024"
  chapters:        
    - index.qmd
    - htmlbasico.qmd
    - referencias.qmd  

bibliography: references.bib

format:
  html:
    theme: cosmo
    lang: pt
  pdf:
    documentclass: scrreprt



