# Summary

## Realidade Virtual em páginas e aplicativos web

- As vantagens, flexibilidade, alcance e potencial de aplicações web baseadas em HTML5/JS/CSS.
- A API (Interface de Programação de Aplicativos) WebXR utilizada pelos headsets VR nas páginas web.
- Exemplos de Plataformas Web que utilizam WebXR:
    - Three.js
    - Babylon.js
    - A-Frame

## Principais características do A-Frame

- Filosofia
- Objetivos
- Usos

## Breve introdução ao HTML/Javascript

- Como se estrutura um arquivo HTML/Javascript básico
- Formas de rodar o arquivo HTML:
    - Página local (editor de texto txt). Usaremos apenas para mostrar os passos iniciais do HTML/Javascript.
    - Servidor web (usaremos o Glitch, mas existem inúmeros outros). Será usado para o desenvolvimento de todo o aplicativo STL.
    - Servidor local (apenas mostraremos, ao final do minicurso, o caminho que estamos adotando em nossos projetos).

## Aplicativo Sol-Terra-Lua em VR com o A-Frame 

Vamos aprender a usar o A-Frame através de um processo mão na massa de construção de um aplicativo VR para visualização do sistema Sol-Terra-Lua (STL).

### Elementos primitivos (*A-Frame primitives*):

Vamos construir alguns elementos primitivos como esferas, cubos e cones e definir alguns de seus atributos via componentes *A-Frame components*.

### Entidades personalizadas (*A-Frame entities*):


